name: Minify JavaScript

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Create package.json
      run: |
        echo '{
          "name": "my-project",
          "version": "1.0.0",
          "description": "",
          "main": "index.js",
          "scripts": {
            "test": "echo \"Error: no test specified\" && exit 1"
          },
          "keywords": [],
          "author": "",
          "license": "ISC",
          "dependencies": {
            "terser": "^5.7.2"
          }
        }' > package.json

    - name: Install Dependencies npm
      run: npm install

    - name: Install Dependencies
      run: npm ci

    - name: Create dist directory
      run: mkdir -p dist

    - name: Minify JavaScript
      run: |
        TAG_NAME=$(basename $GITHUB_REF)
        npx terser customComponents.js -o dist/customComponents-${TAG_NAME}.min.js

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/*
        git commit -m "Minify JavaScript files" -a
        git push
