name: Tag on merge

on:
  pull_request:
    types:
      - closed

jobs:
  criando-tag-e-pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Tag and Release
        id: create_tag
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            lastTag=$(git describe --tags `git rev-list --tags --max-count=1`)
            baseString=$(echo $lastTag | grep -o '[\d.]\+$')
            prefix=$(echo $lastTag | sed "s/$baseString//")
            parts=($(echo $baseString | tr '.' ' '))
            parts[2]=$((parts[2]+1))
            newTag="${prefix}${parts[0]}.${parts[1]}.${parts[2]}"
            git tag $newTag ${{ github.event.pull_request.merge_commit_sha }}
            echo "::set-output name=newTag::$newTag"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Tag
        run: |
          git push origin ${{ steps.create_tag.outputs.newTag }}
