name: Tag on merge

on:
  pull_request:
    types:
      - closed

jobs:

  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: scripts
        run: npm install

  create_tag_and_draft_release:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        working-directory: scripts
        run: node create_release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_release:
    needs: [create_tag_and_draft_release, install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
        working-directory: scripts
        run: node publish_release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_ID: ${{ needs.create_tag_and_draft_release.outputs.create_release }}

  build-min-js:
    needs: [publish_release, install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Create dist directory
        run: mkdir -p dist

      - name: Get Tag Name
        id: get_tag
        run: |
          TAG_NAME=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" -H "Authorization: Bearer ${{ secrets.TOKEN_ACTIONS }}" | jq -r '.tag_name')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Minify JavaScript
        working-directory: scripts
        run: |
          TAG_NAME=$(basename $GITHUB_REF)
          npx terser ../src/customComponents.js -o ../dist/customComponents-${TAG_NAME}.min.js

      - name: Checkout main branch
        run: git checkout main

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/*
          git commit -m "Minify JavaScript files" -a
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACTIONS }}

      - name: Get Release ID
        id: get_release
        run: |
          RELEASE_ID=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" -H "Authorization: Bearer ${{ secrets.TOKEN_ACTIONS }}" | jq -r '.id')
          echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}/assets{?name,label}
          asset_path: dist/customComponents-${{ env.TAG_NAME }}.min.js
          asset_name: customComponents-${{ env.TAG_NAME }}.min.js
          asset_content_type: application/javascript
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACTIONS }}
