name: Tag on merge

on:
  pull_request:
    types:
      - closed

jobs:
  create_tag_and_draft_release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Draft Release
        id: create_release
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // Desestruturação do objeto context.repo para obter o proprietário e o repositório
            const { owner, repo } = context.repo

            // Obtenção do número do pull request a partir do payload do contexto
            const prNumber = context.payload.pull_request.number

            // Obtenção das labels do pull request atual. A função listLabelsOnIssue é chamada com o proprietário, o repositório e o número do pull request.
            // O resultado é mapeado para obter apenas os nomes das labels.
            const labels = (await github.issues.listLabelsOnIssue({ owner, repo, issue_number: prNumber })).data.map(label => label.name)

            // Obtenção da última tag do repositório. A função listTags é chamada com o proprietário e o repositório.
            // O resultado é mapeado para obter apenas os nomes das tags, que são então ordenados e a última é selecionada.
            const lastTag = (await github.repos.listTags({ owner, repo })).data.map(tag => tag.name).sort().pop()

            // Extração da base da última tag (parte antes do hífen) e divisão em partes (versão major, minor e patch)
            const baseString = lastTag.match(/[\d.]+-\d+/)[0]
            const parts = baseString.split('-')[0].split('.').map(Number)

            // Extração do número da última tag (parte após o hífen) e incremento para obter o número da nova tag
            const lastTagNumber = parseInt(lastTag.match(/-(\d+)$/)?.[1])
            const newTagNumber = isNaN(lastTagNumber) ? 1 : lastTagNumber + 1

            // Verificação das labels do pull request para determinar como a versão deve ser incrementada
            if (labels.includes('upgrade')) {
              // Se a label 'upgrade' estiver presente, incrementa a versão major e zera a minor e a patch
              parts[0] += 1
              parts[1] = 0
              parts[2] = 0
            } else {
              if (labels.includes('enhancement')) {
                // Se a label 'enhancement' estiver presente, incrementa a versão minor e zera a patch
                parts[1] += 1
                parts[2] = 0
              } else if (labels.includes('bug') || labels.includes('documentation')) {
                // Se as labels 'bug' ou 'documentation' estiverem presentes, incrementa a versão patch
                parts[2] += 1
              } else {
                // Se nenhuma das labels anteriores estiver presente, o script é encerrado
                return
              }
            }

            // Criação da nova tag a partir das partes da versão e do número da tag
            const newTag = `${parts.join('.')}-${newTagNumber}`

            // Criação da referência para a nova tag no repositório
            const tagRef = await github.git.createRef({
              owner,
              repo,
              ref: `refs/tags/${newTag}`,
              sha: context.payload.pull_request.merge_commit_sha,
            })

  update_release_draft:
    needs: create_tag_and_draft_release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_release:
    needs: update_release_draft
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish Release
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // Desestruturação do objeto context.repo para obter o proprietário e o repositório
            const { owner, repo } = context.repo

            // Obtenção da lista de releases do repositório atual
            const releases = await github.repos.listReleases({
                owner,
                repo,
            })

            // Busca por um release que ainda está em rascunho (draft)
            const draftRelease = releases.data.find(release => release.draft)

            // Obtenção do número do pull request a partir do payload do contexto
            const prNumber = context.payload.pull_request.number

            // Obtenção das labels do pull request atual. A função listLabelsOnIssue é chamada com o proprietário, o repositório e o número do pull request.
            // O resultado é mapeado para obter apenas os nomes das labels.
            const labels = (await github.issues.listLabelsOnIssue({ owner, repo, issue_number: prNumber })).data.map(label => label.name)

            // Se um release em rascunho for encontrado
            if (draftRelease) {
                // Obtenção da última tag do repositório
                const lastTag = (await github.repos.listTags({ owner, repo })).data.map(tag => tag.name).sort().pop()

                // Atualização do release em rascunho com a última tag, alterando o nome para remover hífens e substituí-los por parênteses
                // Além disso, o release é marcado como não sendo mais um rascunho (draft: false) e como pré-release (prerelease: true)
                await github.repos.updateRelease({
                    owner,
                    repo,
                    release_id: draftRelease.id,
                    tag_name: lastTag,
                    name: lastTag.trim().replace(/-/g, ' (') + ')',
                    draft: false,
                    prerelease: !labels.includes('release'),
                })
            }

  update_branch_release:
    needs: publish_release
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main'

      - name: Create and push branch
        run: |
          git checkout -b ${BRANCH_NAME} || git checkout ${BRANCH_NAME}
          git reset --hard origin/main
          git push --force origin ${BRANCH_NAME}
        env:
          BRANCH_NAME: latest-release

  sync_labels:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
    - uses: actions/checkout@v2
    - uses: micnncim/action-label-syncer@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        manifest: .github/labels.yml
        prune: true

  build-min-js:
    needs: update_release_draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create package.json
        run: |
          echo '{
            "name": "my-project",
            "version": "1.0.0",
            "description": "",
            "main": "index.js",
            "scripts": {
              "test": "echo \"Error: no test specified\" && exit 1"
            },
            "keywords": [],
            "author": "",
            "license": "ISC",
            "dependencies": {
              "terser": "^5.7.2"
            }
          }' > package.json

      - name: Install Dependencies npm
        run: npm install

      - name: Install Dependencies
        run: npm ci

      - name: Create dist directory
        run: mkdir -p dist

      - name: Get Tag Name
        id: get_tag
        run: |
          TAG_NAME=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases?per_page=1" -H "Authorization: Bearer ${{ secrets.TOKEN_ACTIONS }}" | jq -r '[.[] | select(.prerelease == true)][0].tag_name')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Minify JavaScript
        run: |
          npx terser src/customComponents.js -o dist/customComponents-${{ env.TAG_NAME }}.min.js

      - name: Checkout main branch
        run: git checkout main

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/*
          git commit -m "Minify JavaScript files" -a
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACTIONS }}

      - name: Get Release ID
        id: get_release
        run: |
          RELEASE_ID=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases?per_page=1" -H "Authorization: Bearer ${{ secrets.TOKEN_ACTIONS }}" | jq -r '[.[] | select(.prerelease == true)][0].id')
          echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}/assets{?name,label}
          asset_path: dist/customComponents-${{ env.TAG_NAME }}.min.js
          asset_name: customComponents-${{ env.TAG_NAME }}.min.js
          asset_content_type: application/javascript
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACTIONS }}
