name: Tag on merge

on:
  pull_request:
    types:
      - closed

jobs:
  criando-tag-e-pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Tag and Release
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (context.payload.pull_request.merged) {
              const { owner, repo } = context.repo
              const lastTag = (await github.repos.listTags({
                owner,
                repo,
              })).data.map(tag => tag.name).sort().pop()
              const baseString = lastTag.match(/[\d.]+$/)[0]
              const prefix = lastTag.replace(baseString, '')
              const parts = baseString.split('.').map(Number);
              parts[2] += 1; // Incrementa a parte menor da versão
              const newTag = `${prefix}${parts.join('.')}`;
              const tagRef = await github.git.createRef({
                owner,
                repo,
                ref: `refs/tags/${newTag}`,
                sha: context.payload.pull_request.merge_commit_sha,
              })
              await github.repos.createRelease({
                owner,
                repo,
                tag_name: newTag,
                name: newTag,
                draft: false,
                prerelease: true,
              })
            }
